<script setup lang="ts">
import {ref,inject,onMounted,onUnmounted} from 'vue';
import {languageKey,languageData,type Languages} from './baseline-language';
import type {Locale} from './contracts';
const model=inject<Languages>(languageKey)!;
const open=ref(false),host=ref<HTMLElement|null>(null);
const name=(code:string)=>languageData.names[model.snapshot.locale]?.[code]||languageData.names['en-US'][code]||code;
function outside(event:MouseEvent){if(!host.value?.contains(event.target as Node))open.value=false;}
async function choose(code:string){if(await model.choose(code as Locale))open.value=false;}
onMounted(()=>document.addEventListener('click',outside));
onUnmounted(()=>document.removeEventListener('click',outside));
</script>
<template><div class="key">语言</div><div class="languagePicker" :class="{open}" id="languagePicker" ref="host"><button class="select languageCurrent" id="languageCurrent" type="button" aria-haspopup="listbox" :aria-expanded="open" @click="open=!open"><span class="languageFlag" id="languageCurrentFlag" v-html="languageData.flags[model.snapshot.options.find(o=>o.code===model.snapshot.locale)?.flag||'cn']"></span><span class="languageCurrentName" id="languageCurrentName">{{name(model.snapshot.locale)}}</span><span class="languageChevron"></span></button><div class="languageMenu" id="languageMenu" role="listbox" aria-label="选择语言"><button v-for="option in model.snapshot.options" :key="option.code" type="button" class="languageRow" :class="{current:option.code===model.snapshot.locale}" role="option" :aria-selected="option.code===model.snapshot.locale" :data-language-code="option.code" @click="choose(option.code)"><span class="languageFlag" v-html="languageData.flags[option.flag]||languageData.flags.cn"></span><span>{{name(option.code)}}</span><span class="languageNative" data-i18n-user>{{option.code===model.snapshot.locale?'':option.native_name}}</span><span class="languageAction" :title="model.text(!option.installed&&!option.built_in?'下载语言包':option.code===model.snapshot.locale?'当前语言':'切换语言')" :aria-label="model.text(!option.installed&&!option.built_in?'下载语言包':option.code===model.snapshot.locale?'当前语言':'切换语言')"><svg v-if="option.code===model.snapshot.locale" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.2"><path d="m5 12 4 4L19 6"/></svg><span v-else-if="model.downloading===option.code||option.state==='downloading'" class="languageSpinner"></span><svg v-else-if="option.state==='failed'" class="languageError" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M12 3 2 21h20z"/><path d="M12 9v5m0 3h.01"/></svg><svg v-else-if="!option.installed&&!option.built_in&&option.downloadable" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M12 3v12m0 0 5-5m-5 5-5-5M5 21h14"/></svg></span></button></div><select class="languageSelectCompat" id="language" tabindex="-1" aria-hidden="true" :value="model.snapshot.locale" @change="choose(($event.target as HTMLSelectElement).value)"><option v-for="option in model.snapshot.options" :key="option.code" :value="option.code">{{model.snapshot.locale==='en-US'?option.english_name:option.native_name}}</option></select></div></template>
